export const babyProducts = [
  {
    id: 1,
    title: "Baby Hooded Towel – Bear Ears",
    description:
      "A cozy hooded towel made from ultra-soft cotton terry, featuring adorable bear ears to keep your baby snug after bath time.",
    category: "baby-bath",
    price: 149.99,
    discountPercentage: 10.0,
    rating: 4.8,
    stock: 45,
    tags: ["bath", "towel", "bear", "baby essentials"],
    sku: "BAB-TWL-BEAR-001",
    weight: 0.4,
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 3–5 days",
    availabilityStatus: "In Stock",
    thumbnail: "/images/image-1.png",
  },
  {
    id: 2,
    title: "Cotton Baby Pajamas – Star Dreams",
    description:
      "Dreamy two-piece pajama set made from breathable organic cotton with gentle star patterns for a restful night’s sleep.",
    category: "baby-sleepwear",
    price: 199.99,
    discountPercentage: 15.0,
    rating: 4.7,
    stock: 58,
    tags: ["pajamas", "organic cotton", "sleepwear"],
    sku: "BAB-PJM-STRD-002",
    weight: 0.3,
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 4 days",
    availabilityStatus: "In Stock",
    thumbnail: "/images/image-2.png",
  },
  {
    id: 3,
    title: "Baby Bodysuit – Woodland Animals",
    description:
      "A charming short-sleeve bodysuit featuring playful woodland animals, crafted from 100% organic cotton.",
    category: "baby-bodysuits",
    price: 129.99,
    discountPercentage: 5.0,
    rating: 4.9,
    stock: 72,
    tags: ["bodysuit", "organic cotton", "animals"],
    sku: "BAB-BDY-WLD-003",
    weight: 0.25,
    warrantyInformation: "6 month warranty",
    shippingInformation: "Ships in 2–3 days",
    availabilityStatus: "In Stock",
    thumbnail: "/images/image-3.png",
  },
  {
    id: 4,
    title: "Baby Romper – Ocean Breeze",
    description:
      "Lightweight romper designed for summer comfort, featuring ocean wave prints and snap closures for easy changes.",
    category: "baby-rompers",
    price: 179.99,
    discountPercentage: 8.0,
    rating: 4.6,
    stock: 51,
    tags: ["romper", "summer", "ocean"],
    sku: "BAB-RMP-OCN-004",
    weight: 0.28,
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 5 days",
    availabilityStatus: "In Stock",
    thumbnail: "/images/image-4.png",
  },
  {
    id: 5,
    title: "Knitted Baby Beanie – Little Bunny",
    description:
      "Hand-knitted beanie with soft bunny ears, perfect for keeping little heads warm and adorable.",
    category: "baby-accessories",
    price: 89.99,
    discountPercentage: 12.0,
    rating: 4.8,
    stock: 40,
    tags: ["beanie", "knitwear", "winter"],
    sku: "BAB-BNY-BEAN-005",
    weight: 0.1,
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 3 days",
    availabilityStatus: "In Stock",
    thumbnail: "/images/image-5.png",
  },
  {
    id: 6,
    title: "Baby Blanket – Cloud Soft",
    description:
      "Super-soft fleece blanket designed for warmth and comfort, perfect for nap time and stroller rides.",
    category: "baby-bedding",
    price: 159.99,
    discountPercentage: 10.0,
    rating: 4.9,
    stock: 68,
    tags: ["blanket", "fleece", "comfort"],
    sku: "BAB-BLN-CLD-006",
    weight: 0.6,
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships in 2–4 days",
    availabilityStatus: "In Stock",
    thumbnail: "/images/image-6.png",
  },
  {
    id: 7,
    title: "Baby Overalls – Denim Delight",
    description:
      "Classic denim overalls with adjustable straps and side snaps, designed for comfort and style.",
    category: "baby-outfits",
    price: 229.99,
    discountPercentage: 20.0,
    rating: 4.5,
    stock: 37,
    tags: ["denim", "overalls", "casual"],
    sku: "BAB-OVR-DEN-007",
    weight: 0.35,
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 5 days",
    availabilityStatus: "In Stock",
    thumbnail: "/images/image-7.png",
  },
  {
    id: 8,
    title: "Baby Sleepsack – Cozy Clouds",
    description:
      "A wearable blanket with secure zip closure and cloud patterns, ensuring safe and cozy sleep.",
    category: "baby-sleepwear",
    price: 189.99,
    discountPercentage: 10.0,
    rating: 4.8,
    stock: 44,
    tags: ["sleep sack", "sleepwear", "baby"],
    sku: "BAB-SLP-CLD-008",
    weight: 0.4,
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 3–5 days",
    availabilityStatus: "In Stock",
    thumbnail: "/images/image-8.png",
  },
  {
    id: 9,
    title: "Baby Mittens – Tiny Hands",
    description:
      "Soft cotton mittens to prevent scratching and keep your baby's hands warm all day long.",
    category: "baby-accessories",
    price: 59.99,
    discountPercentage: 5.0,
    rating: 4.7,
    stock: 80,
    tags: ["mittens", "cotton", "warmth"],
    sku: "BAB-MIT-TIN-009",
    weight: 0.05,
    warrantyInformation: "6 month warranty",
    shippingInformation: "Ships in 2 days",
    availabilityStatus: "In Stock",
    thumbnail: "/images/image-9.png",
  },
  {
    id: 10,
    title: "Baby Jacket – Little Explorer",
    description:
      "A lightweight jacket with soft inner lining and fun adventure-themed patches for your little explorer.",
    category: "baby-outerwear",
    price: 259.99,
    discountPercentage: 18.0,
    rating: 4.9,
    stock: 35,
    tags: ["jacket", "outerwear", "adventure"],
    sku: "BAB-JCK-EXP-010",
    weight: 0.5,
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships in 5–7 days",
    availabilityStatus: "In Stock",
    thumbnail: "/images/image-10.png",
  },
  // Continue to id: 50
  ...Array.from({ length: 40 }, (_, i) => ({
    id: i + 11,
    title: [
      "Baby Booties – Snow Bear",
      "Baby Bib Set – Safari Friends",
      "Floral Baby Dress – Summer Bloom",
      "Baby Hoodie – Little Fox",
      "Baby Leggings – Soft Stripe",
      "Baby Onesie – Rainbow Smiles",
      "Baby Hat – Sunshine Days",
      "Baby Romper – Tropical Hugs",
      "Baby Swaddle Set – Moonlight Wrap",
      "Baby Pants – Cozy Knit",
      "Baby Bodysuit – Dreamy Dots",
      "Baby Cardigan – Autumn Hugs",
      "Baby Shorts – Beach Day",
      "Baby Pajamas – Cotton Clouds",
      "Baby Beanie – Tiny Star",
      "Baby Set – Gentle Meadow",
      "Baby Socks – Happy Feet",
      "Baby Blanket – Little Stars",
      "Baby Romper – Dino Dreams",
      "Baby Overalls – Blue Sky",
      "Baby Gown – Sleepy Moon",
      "Baby Booties – Cozy Sheep",
      "Baby Dress – Fairy Garden",
      "Baby T-shirt – Smiley Sun",
      "Baby Pants – Forest Trail",
      "Baby Hat – Little Sailor",
      "Baby Hoodie – Wild Forest",
      "Baby Mittens – Polar Hugs",
      "Baby Sleepsuit – Starry Night",
      "Baby Leggings – Rainbow Stripes",
      "Baby Romper – Safari Adventure",
      "Baby Onesie – Sweet Dreams",
      "Baby Blanket – Cotton Cloud",
      "Baby Dress – Peach Petals",
      "Baby Pants – Gentle Sky",
      "Baby Set – Forest Dreams",
      "Baby Booties – Snow Bunny",
      "Baby Romper – Honey Bee",
      "Baby Bodysuit – Cotton Heart",
      "Baby Beanie – Ocean Waves",
    ][i],
    description:
      "A premium baby clothing item designed for comfort, softness, and adorable style. Made from safe, breathable materials ideal for delicate skin.",
    category: "baby-clothing",
    price: (Math.random() * 100 + 100).toFixed(2),
    discountPercentage: (Math.random() * 20).toFixed(2),
    rating: (Math.random() * 0.5 + 4.5).toFixed(2),
    stock: Math.floor(Math.random() * 80 + 20),
    tags: ["baby", "clothing", "soft", "adorable"],
    sku: `BAB-${String(i + 11).padStart(3, "0")}`,
    weight: 0.3,
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 3–5 days",
    availabilityStatus: "In Stock",
    thumbnail: `/images/image-${i + 11}.jpeg`,
  })),
];
