import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/header";
import CartSidebar from "@/components/cart/cart-sidebar";
import { getSessionUser } from "@/data/user";
import { IUser } from "@/definitions/user";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = (await getSessionUser()) as IUser;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ Global Header */}
        <Header user={user} />
        {/* ✅ Main content */}
        <div className="pt-16 bg-lunar-green-50">{children}</div>
        {/* {children} */}
        {/* ✅ Global Cart Sidebar */}
        <CartSidebar />
      </body>
    </html>
  );
}
